# Generated by Django 4.1.4 on 2022-12-21 10:49

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default=django.utils.timezone.now, max_length=255, verbose_name="image"
            ),
            preserve_default=False,
        ),
    ]
