# Generated by Django 4.1.4 on 2022-12-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phonenumber",
            field=models.BigIntegerField(default=0, verbose_name="phone number"),
        ),
    ]
