# Generated by Django 4.1.4 on 2022-12-23 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_profile_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(default=datetime.date.today, verbose_name="dob"),
        ),
    ]
