# Generated by Django 4.1.4 on 2023-05-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_profile_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_engineer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_user",
            field=models.BooleanField(default=True),
        ),
    ]
